language: ruby
rvm:
- 2.6.3

addons:
  ssh_known_hosts: srv.svtplay-dl.se

before_install:
- chmod +x ./cibuild

script: ./cibuild

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy
  on:
    branch: master

sudo: false
