name: Build and deploy Jekyl

on:
  push:


jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }} 
    # Standard usage
    - uses:  lemonarc/jekyll-action@1.0.0

    - name: check
      run: ls ./_site/

    - name: test
      run: rsync --version
